### ISSUE TITLE
Need instructions on how to run on Firefox OS

### ISSUE THREAD

**Issue by shinglyu** [janthiemen/nisi#1]
Hi @janthiemen, I've come across your app in Firefox Marketplace. I would like to contribute some styling and UX tweaks, but not sure how to run the code in github on Firefox OS. Could you help? Thanks.

**Comment by janthiemen** [comment]
Hello,
This is the WebOS version of NISI, I forgot to upload the Firefoxos version, sorry for that. You can find it here: https://github.com/janthiemen/nisi_fxos. It can be installed just like every other FirefoxOS app. Again my apologies for the confusion.
Jan Thiemen

**Comment by shinglyu** [comment]
Thank you! I love the fxos version.

Jan Thiemen notifications@github.com 於 2015年7月13日 週一 下午11:44寫道：
